.TH "xrestop" 1
.SH NAME
xrestop \- monitor server resources used by X11 clients
.SH SYNOPSIS
.B xrestop
\-help
.br
.B xrestop
[ \fB\-display\fP display ] [ \fB\-\-batch\fP ] [ \fB\-\-delay\-time\fP seconds ]
.SH DESCRIPTION
Xrestop uses the X\-Resource extension to provide 'top'\-like statistics of 
each connected X11 client's server\-side resource usage.  It is intended 
as a developer tool to aid more efficient server resource usage and 
debug server\-side resource leakage.
.SH OPTIONS
.TP
\fB\-\-help\fP
Show usage.
.TP
\fB\-\-display, \-d\fP <display>
Specify X11 display to monitor.
.TP
\fB\-\-delay-time, \-dt\fP <seconds>
Time in seconds between taking samples. Default is 2 seconds. 
.TP
\fB\-\-batch, \-b\fP
Run in batch mode. Slightly more detailed infomation is streamed to 
stdout rather than the usual curses interface. This mode is intended
for debugging a single client with something like 
.br
  xrestop \-b | grep \-A 14 appname
.TP
\fB\-\-max\-samples, \-m\fP <count>
Specify number of times to gather and display results.
Default is continuous, which can be set with 0 (zero).
.br
.SH "SEE ALSO"
.BR X (7),
.BR top (1) .
.SH BUGS
The X\-Resource extension is very new and may not be 100% accurate. 
.SH AUTHOR
.B xrestop
was written by Matthew Allum <mallum@handhelds.org>.
